export {
  LexAPI,
  DEFAULT_BASE_URL,
  DEFAULT_TIMEOUT_MS,
  type LexAPIOptions,
  type CallOptions,
} from "./client.js";
export type { RetryOptions } from "./http.js";
export {
  LexAPIError,
  NotFoundError,
  InvalidCelexError,
  InvalidUrlError,
  InvalidParamsError,
  AuthenticationError,
  RateLimitedError,
  TierForbiddenError,
  CreditsExhaustedError,
  UpstreamError,
  TimeoutError,
  InternalServerError,
  NetworkError,
  type ErrorCode,
} from "./errors.js";
export { getCreditUsage, type CreditUsage } from "./credits.js";
export { WebhooksAPI } from "./webhooks.js";
export type {
  ExportParams,
  ExportRow,
  ExportMeta,
  ExportDone,
  ExportHeaderInfo,
  ExportStream,
} from "./export.js";
export type {
  SubscriptionTier,
  Language,
  Domain,
  Subdomain,
  DocumentType,
  Author,
  Procedure,
  TextScope,
  SubscriptionInfo,
  UsageInfo,
  CreditsInfo,
  CreditedResponse,
  InfoSearchFilters,
  InfoResponse,
  IncludeToken,
  IncludeSelection,
  Article,
  Section,
  Recital,
  Annex,
  Table,
  DocumentContent,
  DocumentMetadata,
  Document,
  DocumentTypeCode,
  SearchResult,
  SearchRequest,
  SearchResponse,
  DocumentContentRequest,
  DocumentContentResponse,
  DocumentContentBatchRequest,
  BatchDocumentError,
  DocumentContentBatchResponse,
  RecentDocumentsParams,
  RecentDocumentsResponse,
  DocumentByUrlRequest,
  DocumentByUrlResponse,
  DocumentMetadataRequest,
  DocumentMetadataResponse,
  IdentifierType,
  ResolveResponse,
  CitationType,
  CitationEdgeSummary,
  CitationExtractResponse,
  CitationEdgeDetail,
  CitingDocumentGroup,
  CitedDocumentGroup,
  CitationEdgeParams,
  CitedByResponse,
  CitesResponse,
  CitationNeighbour,
  CitationNetworkParams,
  CitationNetworkResponse,
  CitationStatsTopCited,
  CitationStatsTopCiting,
  CitationStatsResponse,
  CitationPathNode,
  CitationPathResponse,
  RelatedDocument,
  RelatedDocumentsResponse,
  SemanticLanguage,
  SemanticSearchOptions,
  SemanticCaseLawSearchOptions,
  SemanticCaseLawResult,
  SemanticUsageInfo,
  SemanticCaseLawSearchResponse,
  SemanticLegislationResult,
  SemanticLegislationSearchResponse,
  WebhookStatus,
  DeliveryStatus,
  WebhookListItem,
  WebhookDelivery,
  WebhookDetail,
  WebhookListResponse,
  WebhookCreateRequest,
  WebhookUpdateRequest,
  WebhookCreateResponse,
  WebhookUpdateResponse,
  WebhookResponse,
  WebhookTestResponse,
  WebhookDeliveriesParams,
  WebhookDeliveriesResponse,
} from "./types.js";
export { VERSION } from "./version.js";
